# Generated by Django 3.1.1 on 2020-09-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promoApplication.user'),
        ),
    ]
