# Generated by Django 3.1.1 on 2020-09-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoApplication', '0002_promo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_admin': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='promoApplication.user'),
        ),
    ]
